"""Generate statistics.md from the metadata files — the single source of truth
for dataset coverage.

Scans every conference-year JSON under the metadata root and reports, per year:
paper count, PDF completeness, and missing abstracts. Run it against the
canonical data store and commit the regenerated statistics.md; never edit the
numbers by hand.

Usage:
    python postprocessing/generate_statistics.py                  # print to stdout
    python postprocessing/generate_statistics.py --write          # rewrite statistics.md
    python postprocessing/generate_statistics.py --metadata-root /Volumes/MyData/mustcite/metadata
"""

import argparse
import json
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from config import METADATA_DIR  # noqa: E402

# Display names for the summary table.
NAMES = {
    "neurips": "NeurIPS (Neural Information Processing Systems)",
    "icml":    "ICML (International Conference on Machine Learning)",
    "iclr":    "ICLR (International Conference on Learning Representations)",
    "aaai":    "AAAI (AAAI Conference on Artificial Intelligence)",
    "cvpr":    "CVPR (IEEE/CVF Conference on Computer Vision and Pattern Recognition)",
    "iccv":    "ICCV (IEEE/CVF International Conference on Computer Vision)",
    "eccv":    "ECCV (European Conference on Computer Vision)",
    "acl":     "ACL (Annual Meeting of the Association for Computational Linguistics)",
    "emnlp":   "EMNLP (Conference on Empirical Methods in Natural Language Processing)",
    "naacl":   "NAACL (North American Chapter of the ACL)",
    "ijcai":   "IJCAI (International Joint Conference on Artificial Intelligence)",
    "aistats": "AISTATS (International Conference on Artificial Intelligence and Statistics)",
    "colt":    "COLT (Conference on Learning Theory)",
    "uai":     "UAI (Conference on Uncertainty in Artificial Intelligence)",
    "jmlr":    "JMLR (Journal of Machine Learning Research)",
}

# Order conferences as in the README.
ORDER = ["neurips", "icml", "iclr", "aaai", "cvpr", "colt", "uai", "jmlr",
         "aistats", "ijcai", "acl", "emnlp", "naacl", "iccv", "eccv"]


def scan(metadata_root: Path):
    """Return {conf: {year: (papers, pdfs, missing_abstract)}}."""
    stats = {}
    for path in sorted(metadata_root.glob("*/*.json")):
        if path.name.endswith(".bak"):
            continue
        conf = path.parent.name
        year = path.stem.rsplit("_", 1)[-1]
        try:
            papers = json.load(open(path, encoding="utf-8"))
        except Exception as e:
            print(f"[load error] {path}: {e}", file=sys.stderr)
            continue
        n = len(papers)
        pdfs = sum(1 for p in papers if p.get("pdf_downloaded"))
        no_abs = sum(1 for p in papers if not (p.get("abstract") or "").strip())
        stats.setdefault(conf, {})[year] = (n, pdfs, no_abs)
    return stats


def render(stats) -> str:
    confs = [c for c in ORDER if c in stats] + sorted(set(stats) - set(ORDER))
    grand_papers = grand_pdfs = 0

    out = []
    out.append("# Academic Conference Papers Statistics Summary")
    out.append("")
    out.append(f"_Generated by `postprocessing/generate_statistics.py` "
               f"on {date.today().isoformat()}. Do not edit numbers by hand._")
    out.append("")

    # Summary table -----------------------------------------------------------
    out.append("## Coverage Summary")
    out.append("")
    out.append("| Conference | Years | Papers | PDFs |")
    out.append("|------------|-------|--------|------|")
    for conf in confs:
        years = sorted(stats[conf])
        papers = sum(v[0] for v in stats[conf].values())
        pdfs = sum(v[1] for v in stats[conf].values())
        grand_papers += papers
        grand_pdfs += pdfs
        out.append(f"| {conf.upper()} | {years[0]}–{years[-1]} "
                   f"| {papers:,} | {pdfs:,} |")
    out.append(f"| **Total** | | **{grand_papers:,}** | **{grand_pdfs:,}** |")
    out.append("")

    # Per-conference detail ---------------------------------------------------
    out.append("## Detailed Statistics by Conference")
    out.append("")
    for conf in confs:
        out.append(f"### {NAMES.get(conf, conf.upper())}")
        out.append("")
        out.append("| Year | Papers | PDFs | Missing abstracts |")
        out.append("|------|--------|------|-------------------|")
        t_n = t_pdf = t_abs = 0
        for year in sorted(stats[conf]):
            n, pdfs, no_abs = stats[conf][year]
            t_n += n; t_pdf += pdfs; t_abs += no_abs
            out.append(f"| {year} | {n:,} | {pdfs:,} | {no_abs:,} |")
        out.append(f"| **Total** | **{t_n:,}** | **{t_pdf:,}** | **{t_abs:,}** |")
        out.append("")

    return "\n".join(out) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Regenerate statistics.md from the metadata files.")
    parser.add_argument("--metadata-root", type=Path, default=METADATA_DIR,
                        help=f"Metadata directory (default: {METADATA_DIR})")
    parser.add_argument("--write", action="store_true",
                        help="Write statistics.md at the repo root instead of stdout.")
    args = parser.parse_args()

    stats = scan(args.metadata_root)
    if not stats:
        sys.exit(f"No metadata found under {args.metadata_root}")
    md = render(stats)

    if args.write:
        target = Path(__file__).resolve().parents[1] / "statistics.md"
        target.write_text(md, encoding="utf-8")
        print(f"Wrote {target}")
    else:
        sys.stdout.write(md)
