"""Generate the tracked dataset coverage and quality report.

The metadata and PDF trees are the source of truth.  The generated Markdown is
deterministic: use ``--write`` to update it and ``--check`` in automation to
fail when the tracked report or README coverage summary is stale.
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from config import DATA_ROOT, METADATA_DIR  # noqa: E402

NAMES = {
    "neurips": "NeurIPS", "icml": "ICML", "iclr": "ICLR", "aaai": "AAAI",
    "cvpr": "CVPR", "colt": "COLT", "uai": "UAI", "jmlr": "JMLR",
    "aistats": "AISTATS", "ijcai": "IJCAI", "acl": "ACL", "emnlp": "EMNLP",
    "naacl": "NAACL", "iccv": "ICCV", "eccv": "ECCV",
}
ORDER = list(NAMES)
FIELDS = ("title", "authors", "abstract", "bibtex")
README_START = "<!-- BEGIN GENERATED COVERAGE -->"
README_END = "<!-- END GENERATED COVERAGE -->"


def _pdf_file(data_root, pdf_path):
    if not pdf_path:
        return None
    relative = pdf_path[5:] if pdf_path.startswith("data/") else pdf_path
    return data_root / relative


def scan(metadata_root: Path, data_root: Path):
    stats = {}
    errors = []
    for path in sorted(metadata_root.glob("*/*.json")):
        conf = path.parent.name
        try:
            year = int(path.stem.rsplit("_", 1)[-1])
            papers = json.loads(path.read_text(encoding="utf-8"))
            if not isinstance(papers, list):
                raise ValueError("top-level JSON value is not a list")
        except Exception as exc:
            errors.append(f"{path}: {exc}")
            continue

        row = Counter(papers=len(papers))
        ids = Counter(p.get("id") for p in papers if p.get("id"))
        row["duplicate_ids"] = sum(count - 1 for count in ids.values() if count > 1)
        for paper in papers:
            for field in FIELDS:
                if not paper.get(field):
                    row[f"missing_{field}"] += 1
            pdf = _pdf_file(data_root, paper.get("pdf_path"))
            if pdf is None or not pdf.is_file():
                row["missing_pdfs"] += 1
                continue
            try:
                if pdf.stat().st_size < 1024:
                    row["invalid_pdfs"] += 1
                    continue
                with pdf.open("rb") as handle:
                    if handle.read(5) != b"%PDF-":
                        row["invalid_pdfs"] += 1
                        continue
                row["pdfs"] += 1
            except OSError:
                row["invalid_pdfs"] += 1
        stats.setdefault(conf, {})[year] = row

    if errors:
        raise RuntimeError("Metadata scan failed:\n" + "\n".join(errors))
    return stats


def format_years(years):
    years = sorted(years)
    groups = []
    start = previous = years[0]
    for year in years[1:]:
        if year == previous + 1:
            previous = year
            continue
        groups.append(str(start) if start == previous else f"{start}–{previous}")
        start = previous = year
    groups.append(str(start) if start == previous else f"{start}–{previous}")
    return ", ".join(groups)


def _total(rows, key):
    return sum(row[key] for row in rows)


def render_readme_coverage(stats):
    """Render the compact README list from the same canonical scan."""
    confs = [conf for conf in ORDER if conf in stats] + sorted(set(stats) - set(ORDER))
    return "\n".join(
        f"- **{NAMES.get(conf, conf.upper())}** ({format_years(stats[conf])})"
        for conf in confs
    )


def replace_generated_section(text, start, end, content):
    """Replace one marker-delimited generated section."""
    if text.count(start) != 1 or text.count(end) != 1:
        raise ValueError(f"expected exactly one {start!r}/{end!r} marker pair")
    prefix, remainder = text.split(start, 1)
    _, suffix = remainder.split(end, 1)
    return f"{prefix}{start}\n{content}\n{end}{suffix}"


def render(stats):
    confs = [conf for conf in ORDER if conf in stats] + sorted(set(stats) - set(ORDER))
    out = [
        "# Dataset Coverage and Quality Report", "",
        "_Generated by `postprocessing/generate_statistics.py`. Do not edit by hand._", "",
        "## Coverage Summary", "",
        "| Conference | Actual years | Papers | Valid PDFs | Missing abstracts |",
        "|---|---:|---:|---:|---:|",
    ]
    grand = Counter()
    for conf in confs:
        rows = list(stats[conf].values())
        totals = Counter({key: _total(rows, key) for key in (
            "papers", "pdfs", "missing_abstract")})
        grand.update(totals)
        out.append(
            f"| {NAMES.get(conf, conf.upper())} | {format_years(stats[conf])} | "
            f"{totals['papers']:,} | {totals['pdfs']:,} | {totals['missing_abstract']:,} |")
    out.append(
        f"| **Total** | | **{grand['papers']:,}** | **{grand['pdfs']:,}** | "
        f"**{grand['missing_abstract']:,}** |")
    out.extend(["", "## Detailed Quality by Conference", ""])

    columns = ("papers", "pdfs", "missing_pdfs", "invalid_pdfs",
               "missing_abstract", "missing_authors", "missing_bibtex", "duplicate_ids")
    for conf in confs:
        out.extend([
            f"### {NAMES.get(conf, conf.upper())}", "",
            "| Year | Papers | Valid PDFs | Missing PDFs | Invalid PDFs | Missing abstracts | Missing authors | Missing BibTeX | Duplicate IDs |",
            "|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
        ])
        for year, row in sorted(stats[conf].items()):
            out.append("| " + str(year) + " | " + " | ".join(
                f"{row[column]:,}" for column in columns) + " |")
        rows = list(stats[conf].values())
        out.append("| **Total** | " + " | ".join(
            f"**{_total(rows, column):,}**" for column in columns) + " |")
        out.append("")
    return "\n".join(out) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--metadata-root", type=Path, default=METADATA_DIR)
    parser.add_argument("--data-root", type=Path, default=DATA_ROOT)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    try:
        stats = scan(args.metadata_root, args.data_root)
    except RuntimeError as exc:
        print(exc, file=sys.stderr)
        return 1
    if not stats:
        print(f"No metadata found under {args.metadata_root}", file=sys.stderr)
        return 1
    rendered = render(stats)
    repo_root = Path(__file__).resolve().parents[1]
    target = repo_root / "statistics.md"
    readme = repo_root / "README.md"
    try:
        readme_rendered = replace_generated_section(
            readme.read_text(encoding="utf-8"), README_START, README_END,
            render_readme_coverage(stats))
    except (OSError, ValueError) as exc:
        print(f"Cannot update README coverage: {exc}", file=sys.stderr)
        return 1
    if args.write:
        target.write_text(rendered, encoding="utf-8")
        readme.write_text(readme_rendered, encoding="utf-8")
        print(f"Wrote {target}")
        print(f"Updated coverage in {readme}")
    elif args.check:
        stale = False
        if not target.is_file() or target.read_text(encoding="utf-8") != rendered:
            print(f"{target} is stale; run with --write", file=sys.stderr)
            stale = True
        if readme.read_text(encoding="utf-8") != readme_rendered:
            print(f"README coverage is stale; run with --write", file=sys.stderr)
            stale = True
        if stale:
            return 1
        print(f"{target} and README coverage are up to date")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
